### ISSUE TITLE
No License for Political Leaning

### ISSUE THREAD

**Issue by turfaa** [klout/opendata#3]
Hi. Why is there no license for policial leaning, like the other dataset?

**Comment by prantik** [comment]
Thanks for bringing this to our attention, fixed it now.

**Comment by jayvdb** [comment]
Would it be acceptable to have a file `LICENSE` at the top of the repository, containing the text of  Creative Commons Attribution 3.0 Unported License ?

That will make the license [machine readable](https://help.github.com/articles/open-source-licensing/) by GitHub, so that GitHub can make it more visible by humans and also allow it to be queried by the search engine.

If so, we would be happy to send the PR to achieve this.

You can see what it will look like on https://github.com/BesutKode/BesutKode.github.io , where it has " CC-BY-4.0 " on the right above the file list.  In your case it would say " CC-BY-3.0 ".
